import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Rubik_Vinyl } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
 
const vinyl = Rubik_Vinyl({
  subsets : ["latin"],
  style : "normal",
  weight : "400",
  variable : '--font-vinyl'
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dizzy Blog",
  description: "Generated by Fiza Rafakat",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${vinyl.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f3f1f6]  max-w-[1440px] mx-auto`}
      >
        {children}
      </body>
    </html>
  );
}
